server:
  debug: False
  token: 'access_token'
  allowed_hosts:
    - 'localhost'
    - '127.0.0.1'
    - '0.0.0.0'
site:
  title: 'qwerty'
  copyright: '2018'
  ICP: 'ICP'
user:
  nickname: 'nickname'
  avatar: 'avatar_link'
  email: 'xxx@yyy.com'
  github: 'zhangjie2012'
  social:
    - label: 'label1'
      link: 'link1'
    - label: 'label2'
      link: 'link2'
  title: 'programmer'
  career: 'game, finance'
  city: 'Hangzhou'
db:
  name: 'qwerty'
  user: 'root'
  passwd: 'qwerty-pwd'
  host: '127.0.0.1'
  port: '3306'
log:
  level: 'DEBUG'
  filepath: '/data/log/qwerty.log'
  max_bytes: 5000000  # 5M
  backup_count: 5
backup:
  path: '/data/backup/qwerty/'
